<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Render\Element;

/*
 * Implementation of hook_theme
 */
function video_theme() {
  return array(
    // Theme functions in video.module.
    'video_formatter' => array(
      'variables' => array('path' => NULL, 'video_style' => NULL)
    ),
  );
}

/**
 * Prepares variables for video widget templates.
 *
 * Default template: video-widget.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: A render element representing the video field widget.
 */
function template_preprocess_video_widget(&$variables) {
  $element = $variables['element'];
  $variables['attributes'] = array('class' => array('video-widget', 'form-managed-file', 'clearfix'));
  if (!empty($element['fids']['#value'])) {
    $file = reset($element['#files']);
    $element['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . format_size($file->getSize()) . ')</span> ';
  }
  $variables['data'] = array();
  foreach (Element::children($element) as $child) {
    $variables['data'][$child] = $element[$child];
  }

}

/**
 * Prepares variables for video formatter templates.
 *
 * Default template: video-formatter.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An ImageItem object.
 *   - item_attributes: An optional associative array of html attributes to be
 *     placed in the img tag.
 *   - video_style: An optional video style.
 *   - path: An optional array containing the link 'path' and link 'options'.
 */
function template_preprocess_video_formatter(&$variables) {
  if ($variables['video_style']) {
    $variables['video'] = array(
      '#theme' => 'video_style',
      '#style_name' => $variables['video_style'],
    );
  } else {
    $variables['video'] = array(
      '#theme' => 'video',
    );
  }
  $variables['video']['#attributes'] = $variables['item_attributes'];
  $item = $variables['item'];
  if (($entity = $item->entity) && empty($item->uri)) {
    $variables['video']['#uri'] = $entity->getFileUri();
  } else {
    $variables['video']['#uri'] = $item->uri;
  }
  // The link path and link options are both optional, but for the options to be
  // processed, the link path must at least be an empty string.
  // @todo Add support for route names.
  $variables['url'] = NULL;
  if (isset($variables['path']['path'])) {
    $path = $variables['path']['path'];
    $options = isset($variables['path']['options']) ? $variables['path']['options'] : array();
    $variables['url'] = _url($path, $options);
  }
}
